# Generated by Django 4.0.4 on 2022-05-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Ник посетителя')),
                ('real_name', models.CharField(blank=True, max_length=200, verbose_name='Реальное имя посетителя')),
                ('access', models.BooleanField(default=False, verbose_name='Доступ')),
                ('key', models.CharField(default='20220516173915278795', max_length=20, verbose_name='секретный ключ')),
            ],
        ),
    ]
