# Generated by Django 4.0.4 on 2022-05-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0002_alter_customer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='key',
            field=models.CharField(default='20220516173923808580', max_length=20, verbose_name='секретный ключ'),
        ),
    ]
