# Generated by Django 4.0.4 on 2022-05-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0003_alter_customer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='key',
            field=models.CharField(default='11111111111111111111', max_length=20, verbose_name='секретный ключ'),
        ),
    ]
