# Generated by Django 4.0.4 on 2022-05-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0004_alter_customer_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit', models.DateTimeField(auto_now_add=True, verbose_name='Время входа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='qpass.customer', verbose_name='Лог посещений')),
            ],
        ),
    ]
