# Generated by Django 4.0.4 on 2022-05-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0005_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Ник посетителя'),
        ),
    ]
