# Generated by Django 4.0.4 on 2022-05-21 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qpass', '0008_alter_logs_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logs',
            options={'ordering': ('-visit',)},
        ),
        migrations.AddField(
            model_name='customer',
            name='master',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
            preserve_default=False,
        ),
    ]
