# Generated by Django 4.0.4 on 2022-09-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0010_alter_logs_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, help_text=100, upload_to='', width_field=100),
        ),
        migrations.AlterField(
            model_name='logs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='qpass.customer', verbose_name='Ник посетителя'),
        ),
    ]
