# Generated by Django 4.0.4 on 2022-09-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0011_alter_customer_options_customer_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, help_text=100, upload_to='photo/', width_field=100),
        ),
    ]
