# Generated by Django 4.0.4 on 2022-09-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0013_alter_customer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
    ]
