# Generated by Django 4.0.4 on 2022-09-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0014_remove_customer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photo/', verbose_name='Фото'),
        ),
    ]
