# Generated by Django 4.0.4 on 2022-10-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0015_customer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дополнительная информация'),
        ),
    ]
