# Generated by Django 4.0.4 on 2022-10-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0016_customer_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='desc',
        ),
    ]
