# Generated by Django 4.0.4 on 2022-10-25 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0017_remove_customer_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_id', models.CharField(default=uuid.UUID('49631522-a3ba-4229-a726-4ba795a3f0ce'), max_length=128, verbose_name='ID устройства')),
            ],
        ),
    ]
