# Generated by Django 4.0.4 on 2022-11-01 23:07

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('qpass', '0018_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата, время создания id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='dev_id',
            field=models.CharField(default=uuid.UUID('3d3c8804-6166-4d44-8760-487108aaf4f9'), max_length=128, verbose_name='ID устройства'),
        ),
    ]
