version: '3.3'
services:

  web:
    build:
      context: ./qr_pass
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - web

volumes:
  static:
  media:
